giphy:
  # Public beta key from https://github.com/giphy/GiphyAPI#parameters
  api_key: dc6zaTOxFJmzC

chucknorris:
  mentors:
    - '@cyril_lakech'
    - '@yannirbah'
    - '@gierschv'
    - '@Todiann'
    - '@TheDamfr'
    - '@Judith_Kh'

  pictures:
    TheDamfr: http://i.imgur.com/VM4Qy5v.jpg
    yannirbah: http://i.imgur.com/HNBaJkj.jpg

kitten:
  messages:
    - Meouu~~
    - Maaaaaaaouuuu!
    - Meouw... grrr
    - Mewouuuu!
    - Grrrr..... meoouuuuuuu!
    - Gr.....rrrrr!

twitter:
  consumer_key: ''
  consumer_key: ''
  access_token: ''
  access_token_secret: ''

bot:
  account: SWLilleHxCTeam
